steps:
  - records:
      equals: "indent 2"
      first_field: "indent 2"
      field_comment: 2
      deriving: 2
      via: "indent 2"
  - simple_align:
      cases: always
      top_level_patterns: always
      records: always
      multi_way_if: always
  - imports:
      align: group
columns: 80
newline: native
cabal: true
