[global]
server_name = "@domain@"
database_path = "/data"

address = "0.0.0.0"
port = 8080

allow_registration = true
registration_token = "$REGISTRATION_TOKEN"
new_user_displayname_suffix = ""

single_sso = true

encryption_enabled_by_default_for_room_type = "all"

# protected in caddy
allow_legacy_media = true

dns_passthru_appservices = true

turn_uris = [
	"turns:turn.@domain@?transport=udp",
	"turns:turn.@domain@?transport=tcp",
]

turn_secret = "$TURN_SECRET"

[global.well_known]
client = "https://matrix.@domain@"
server = "matrix.@domain@:443"

[[global.identity_provider]]
brand = "Pocket ID"
issuer_url = "https://id.@domain@"

client_id = "$CLIENT_ID"
client_secret = "$CLIENT_SECRET"
