use_default_settings: true

server:
  limiter: true
  image_proxy: true

ui:
  static_use_hash: true

redis:
  url: redis://redis:6379/0

enabled_plugins:
  - 'Hostnames plugin' # https://docs.searxng.org/src/searx.plugins.hostnames.html

hostnames:
  remove:
    - '(.*\.)?nixos\.wiki$'
