use_default_settings: true

server:
  limiter: false
  image_proxy: true

ui:
  static_use_hash: true

enabled_plugins:
  - 'Hostnames plugin' # https://docs.searxng.org/src/searx.plugins.hostnames.html

hostnames:
  remove:
    - '(.*\.)?nixos\.wiki$'
