APP_NAME = Forgejo
RUN_USER = forgejo
WORK_PATH = /data

[database]
DB_TYPE = postgres
HOST = postgres
NAME = forgejo
USER = forgejo
# PASSWD set via env

[server]
HTTP_PORT = 8080
ROOT_URL = https://git.bunny

START_SSH_SERVER = true
SSH_LISTEN_PORT = 2222
SSH_DOMAIN = forgejo

[service]
DISABLE_REGISTRATION = true
REQUIRE_SIGNIN_VIEW = true

[repository]
ENABLE_PUSH_CREATE_USER = true
ENABLE_PUSH_CREATE_ORG = true

[openid]
ENABLE_OPENID_SIGNIN = false
ENABLE_OPENID_SIGNUP = false

[cron.update_checker]
ENABLED = false

[security]
INSTALL_LOCK = true
# INTERNAL_TOKEN set via env
PASSWORD_HASH_ALGO = argon2

# https://codeberg.org/forgejo/docs/issues/765
[oauth2]
ENABLED = false
# JWT_SECRET set via env
