listen        = "0.0.0.0:8080"
allowed-hosts = [ "attic.@domain@", "attic-default.@domain@" ]
api-endpoint  = "https://attic.@domain@/"

[database]
# set via ATTIC_SERVER_DATABASE_URL

[storage]
type = "local"
path = "/data/storage"

[garbage-collection]
default-retention-period = "1 month"

################################################################################

# copied straight from the default config
[chunking]
# The minimum NAR size to trigger chunking
#
# If 0, chunking is disabled entirely for newly-uploaded NARs.
# If 1, all NARs are chunked.
nar-size-threshold = 65536 # chunk files that are 64 KiB or larger

# The preferred minimum size of a chunk, in bytes
min-size = 16384            # 16 KiB

# The preferred average size of a chunk, in bytes
avg-size = 65536            # 64 KiB

# The preferred maximum size of a chunk, in bytes
max-size = 262144           # 256 KiB