source "@complete_alias@"
while read -r name; do
	complete -F _complete_alias "$name"
done < <(alias -p | sed 's|=.*||; s|.* ||' | grep -v man)

bind 'set enable-bracketed-paste on'
bind 'set completion-ignore-case on'
bind '"\t":menu-complete'
bind 'set menu-complete-display-prefix on'
bind 'set colored-completion-prefix on'
bind 'set show-all-if-ambiguous on'

mycd() {
	z "$@" && ls -A
}
