#!/usr/bin/env sh

xrandr -s 1920x1080

# Switch to DE with caps as CTRL
setxkbmap -layout de -option ctrl:nocaps -option compose:sclk

xrdb "$HOME/.config/xresources" & # Load X resources
setbg &
config-wrapper "$HOME/.config/sxhkd" sxhkd -c & # Bind keys
xset r rate 300 50 & # Speed xrate up
unclutter & # Remove mouse when idle
picom \
	-D 3 \
	--experimental-backends \
	--blur-method gaussian \
	--blur-size 20 \
	--blur-deviation 15 \
	--blur-background-exclude 'name = "slop"' &
dunst & # dunst for notifications
