[General]
auto-profiles = yes

[Mapping analog-stereo-speaker]
description = Speaker
device-strings = hw:%f,0
paths-output = analog-output-speaker
channel-map = left,right
direction = output

[Mapping analog-stereo-headphones]
description = Headphones
device-strings = hw:%f,2
paths-output = analog-output-headphones
channel-map = left,right
direction = output

[Profile output:analog-stereo-headphones+output:analog-stereo-speaker]
description = Multi Output
output-mappings = analog-stereo-headphones analog-stereo-speaker
priority = 70
