#!/usr/bin/env bash
# shellcheck disable=SC2155

export EDITOR="nvim"
export TERMINAL="xst"
export BROWSER="firefox"
export READER="zathura"
export SUDO_ASKPASS="$HOME/.bin/dmenu/dmenupass"

# less/man colors
export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"

export BAT_THEME="ansi"
export MANPAGER="sh -c 'col -bx | bat -l man -p --paging=always'"

export GNUPGHOME="$HOME/.local/share/gnupg"
export XCOMPOSEFILE="$HOME/.config/xcompose"
# export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"

export QT_QPA_PLATFORM=wayland
export SDL_VIDEODRIVER=wayland
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway
export _JAVA_AWT_WM_NONREPARENTING=1
