#!/usr/bin/env bash

# utils
alias ccat="highlight --out-format=ansi"
alias diff="diff --color=auto"
alias grep="grep --color=auto"
alias ip="ip -c"
alias ls="ls -hA --color=auto --group-directories-first"
alias mkdir="mkdir -pv"

# helpers
alias fuck='sudo $(history -p !!)'
alias rl="exec \$SHELL -l"

# larger tools
alias calcurse="calcurse -D ~/.config/calcurse"
alias e="\$EDITOR -p"
alias vim="\$EDITOR -p"
alias f="\$FILE"
alias ffmpeg="ffmpeg -hide_banner"
alias mpv='mpv --input-ipc-server=/tmp/mpvsoc$(date +%s)'
alias web="w3m duckduckgo.com/lite"
alias wine="PULSE_LATENCY_MSEC=60 wine"
alias vf="valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes"

# youtube
alias yt="yt-dlp"
alias ytm="yt -x -o '%(uploader)s - %(title)s.%(ext)s'"

# git
alias d="git --git-dir=\$HOME/.dotfiles/.git --work-tree=\$HOME/.dotfiles"
alias g="git"

# kubernetes
alias k="kubectl"
alias kc="kubectx"
alias kn="kubens"
alias ksvc="kubectl get services -A | grep LoadBalancer"
