#!/usr/bin/env bash
# shellcheck disable=SC2155
command_not_found_handle() {
	((${#BASH_SOURCE[@]} > 1)) && return
	echo "Command $1 not found"
	command -v xlocate >/dev/null || return 127
	local POSSIBLE_PKGS="$(xlocate "bin/$1$" 2>/dev/null)"
	[[ -z "$POSSIBLE_PKGS" ]] && return 127
	echo "Possible packages with $1:"
	echo "$POSSIBLE_PKGS"
}
