#!/usr/bin/env bash
# shellcheck disable=SC1090

COMPLETE_ALIAS="$HOME/.config/bash/complete_alias"

[ -f "$COMPLETE_ALIAS" ] || {
	echo "Downloading complete_alias to $COMPLETE_ALIAS"
	curl -L "https://raw.githubusercontent.com/cykerway/complete-alias/master/complete_alias" \
		-o "$COMPLETE_ALIAS"
	source "$COMPLETE_ALIAS"
}

# complete all aliases
while read -r line; do
	complete -F _complete_alias "$line"
done <<< "$(alias -p | sed "s|=.*||g; s|alias ||g")"
