#!/usr/bin/env bash

undot() {
	[ -L "$1" ] || return "Not a symlink!"
	target="$(readlink "$1")"
	[ -e "$target" ] || return "Target $target does not exist!"
	mv "$target" "$1" || return "Could not restore $1 from $target"
	rmdir -p "$(dirname "$target")"
}

npup() {
	(($# < 1)) && {
		echo "Syntax: npup <file>"
		return 1
	}
	[ ! -r "$1" ] && {
		echo "File $1 not readable!"
		return 1
	}
	curl -F "file=@$1" "https://0x0.st"
}

mycd() {
	cd "$@" && ls
}
alias cd="mycd"

javaver () {
	if [ -z "$1" ]; then
		java -version || java --version
	else
		sudo archlinux-java set "java-$1-openjdk";
	fi
}

merge_packages() {
	comm -23 <(pacman -Qeq | sort) <(pacman -Qttq | sort) | xargs sudo pacman -D --asdeps
}

optional_packages() {
	comm -13 <(pacman -Qeq | sort) <(pacman -Qttq | sort)
}
