#!/usr/bin/env bash

undot() {
	[ -L "$1" ] || return "Not a symlink!"
	target="$(readlink "$1")"
	[ -e "$target" ] || return "Target $target does not exist!"
	mv "$target" "$1" || return "Could not restore $1 from $target"
	rmdir -p "$(dirname "$target")"
}

npup() {
	(($# < 1)) && {
		echo "Syntax: npup <file>"
		return 1
	}
	[ ! -r "$1" ] && {
		echo "File $1 not readable!"
		return 1
	}
	curl -F "file=@$1" "https://0x0.st"
}

mycd() {
	cd "$@" && ls
}
alias cd="mycd"
