#!/usr/bin/env bash

: "${DISPLAY:=:1}"
export DISPLAY

if [ -n "$SSH_CONNECTION" ]; then
	XAUTHORITY="$HOME/.Xauthority"
else
	XAUTHORITY="$HOME/.local/share/sx/xauthority"
fi
export XAUTHORITY

export VFLAGS="-skip-unused"
