#!/usr/bin/env sh

xrandr -s 1920x1080

# Switch to DE with caps as CTRL
setxkbmap -layout de -option ctrl:nocaps

xrdb "$HOME/.config/xresources" & # Load X resources
setbg "$HOME/.config/wall.png" & # Set the background
exec config-wrapper "$HOME/.config/sxhkd" sxhkd -c "/dev/stdin" & # Bind keys
xset r rate 300 50 & # Speed xrate up
unclutter -noevents & # Remove mouse when idle
xcompmgr & # xcompmgr for transparency
dunst & # dunst for notifications

