CYPHT_MODULES="@modules@"

DEBUG_LOG=true

DB_DRIVER=sqlite
DB_SOCKET=/data/cypht.db
DB_PASS=ignored

SESSION_TYPE=PHP
AUTH_TYPE=DB
USER_CONFIG_TYPE=DB

ATTACHMENT_DIR=/data/attachments

ADMIN_USERS=eleonora

COOKIE_DOMAIN=mail.laniakea
COOKIE_PATH=/

DEFAULT_LANGUAGE=en

ENABLE_REDIS=true
ENABLE_MEMCACHED=false

ENCRYPT_AJAX_REQUESTS=true
ENCRYPT_LOCAL_STORAGE=true

DISABLE_OPEN_BASE_DIR=true

DEFAULT_SETTING_TIMEZONE="Europe/Berlin"
DEFAULT_SETTING_ENABLE_KEYBOARD_SHORTCUTS=true

DYNAMIC_HOST=false
DYNAMIC_USER=false

APP_2FA_SECRET="$APP_2FA_SECRET"
