#!/usr/bin/env bash
echo "Installing personal dotfile metapackage..."
pushd "$dotpkg" || exit 1
yay -S --needed --noconfirm "${dep[@]}" "${opt[@]}" # install packages
makepkg -cfi --noconfirm # create & install dotfile metapackage

echo "Installing base-devel-meta..."
yay -S --needed --noconfirm base-devel-meta

popd || exit 1
