server_url: https://headscale.@domain@
listen_addr: 0.0.0.0:8080

noise:
  private_key_path: "/data/noise.key"

prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48

disable_check_updates: true

database:
  type: sqlite3
  sqlite:
    path: "/data/db.sqlite"

policy:
  mode: "file"
  path: "/etc/headscale/policy.jsonc"

dns:
  magic_dns: true
  base_domain: bunny.vpn
  nameservers:
    global:
      - 1.1.1.1
      - 1.0.0.1
      - 9.9.9.9

derp:
  urls:
    - https://controlplane.tailscale.com/derpmap/default

unix_socket: "/data/headscale.sock"

oidc:
  only_start_if_oidc_is_available: true
  issuer: "https://id.@domain@"
  client_id: "7ac720c5-8037-43e9-a17b-e7f0bff15d2a"
  # client_secret set via env
  pkce:
    enabled: true
    method: S256
