port: 7880
bind_addresses:
  - ""

rtc:
  tcp_port: 7881
  port_range_start: 50100
  port_range_end: 50200
  use_external_ip: true
  enable_loopback_candidate: false
  turn_servers:
    - host: "turn.$DOMAIN"
      port: 5349
      protocol: tls
      secret: "$TURN_SECRET"
