name: build-guanyin-iso

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v12
        with:
          extra-conf: |
            substituters = https://cache.nixos.org https://nix-community.cachix.org https://attic.eleonora.gay/default
            trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= default:3FYh8sZV8gWa7Jc5jlP7gZFK7pt3kaHRiV70ySaQ42g=

      - name: Build ISO
        run: nix build -L .#nixosConfigurations.guanyin.config.system.build.isoImage

      - name: Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "guanyin"
          prerelease: false
          title: "Guanyin ISO release"
          files: result/iso/nixos-guanyin-*.iso
