{
  imports = [
    ./attic
    ./authelia
    ./auto-upgrade.nix
    ./avh.nix
    ./caddy
    ./headscale
    ./lldap.nix
    ./mount-dcim.nix
    ./mycorrhiza
    ./photoview.nix
    ./pinlist.nix
    ./postgres
    ./redis.nix
    ./rustdesk
    ./searxng
    ./ssh.nix
    ./synapse
    ./syncthing.nix
    ./tailscaled
    ./vaultwarden.nix
    ./vencloud.nix
  ];
}
